# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
            ],
        ),
    ]
