# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_auto_20170707_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('studenttoclassid', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SC_Student', to='onlinetest.Studnet')),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SC_Subject', to='onlinetest.Subject')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper_content',
            options={'verbose_name': 'papercontent'},
        ),
        migrations.AlterModelOptions(
            name='paperinfo',
            options={'verbose_name': 'paperinfo'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'questionbank'},
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='semester',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
