# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0003_auto_20170707_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studnet',
            name='grade',
        ),
    ]
