# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0004_remove_studnet_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='chioce',
            new_name='choice',
        ),
    ]
