# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0005_auto_20170709_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
