# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0006_auto_20170710_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='date',
            field=models.DateField(auto_now_add=True, max_length=20),
        ),
    ]
