# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0007_auto_20170710_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
