# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0008_auto_20170710_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper_content',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_class',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject_teacher',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
