# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0010_auto_20170711_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_content',
            name='score',
            field=models.SmallIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='score',
            field=models.SmallIntegerField(max_length=20),
        ),
    ]
